### PR TITLE
Introduce Aether to download plugins for IDEX-3241

### PR DESCRIPTION
**Pull request by benoitf**

### CODE REVIEW

**Comment by skabashnyuk** [comment]
can you give groupid and artifactid?

**Comment by benoitf** [comment]
what format are you expecting ?

**Comment by skabashnyuk** [comment]
maven dependency is ok for me

**Comment by benoitf** [comment]
<dependency>
            <groupId>org.eclipse.aether</groupId>
            <artifactId>aether-api</artifactId>
            <version>1.0.2.v20150114</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.aether</groupId>
            <artifactId>aether-connector-basic</artifactId>
            <version>1.0.2.v20150114</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.aether</groupId>
            <artifactId>aether-impl</artifactId>
            <version>1.0.2.v20150114</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.aether</groupId>
            <artifactId>aether-spi</artifactId>
            <version>1.0.2.v20150114</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.aether</groupId>
            <artifactId>aether-transport-file</artifactId>
            <version>1.0.2.v20150114</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.aether</groupId>
            <artifactId>aether-transport-http</artifactId>
            <version>1.0.2.v20150114</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.aether</groupId>
            <artifactId>aether-util</artifactId>
            <version>1.0.2.v20150114</version>
        </dependency>

**Comment by skabashnyuk** [comment]
is this all Eclipse project artifacts? Can you confirm

**Comment by benoitf** [comment]
yes these one are eclipse artifacts

**Comment by skabashnyuk** [comment]
LGTM

**Comment by benoitf** [comment]
Can you merge PR ?

**Pull request merged**
