### PR TITLE
Introduce maven aether provider for IDEX-3241

### PR DESCRIPTION
**Pull request by benoitf**

### CODE REVIEW

**Comment by skabashnyuk** [comment]
can you provide groupid and artifactid?

**Comment by benoitf** [comment]
what's the version that you're expecting for
```
       <dependency>
            <groupId>org.eclipse.aether</groupId>
            <artifactId>aether-api</artifactId>
            <version>1.0.2.v20150114</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.aether</groupId>
            <artifactId>aether-connector-basic</artifactId>
            <version>1.0.2.v20150114</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.aether</groupId>
            <artifactId>aether-impl</artifactId>
            <version>1.0.2.v20150114</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.aether</groupId>
            <artifactId>aether-spi</artifactId>
            <version>1.0.2.v20150114</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.aether</groupId>
            <artifactId>aether-transport-file</artifactId>
            <version>1.0.2.v20150114</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.aether</groupId>
            <artifactId>aether-transport-http</artifactId>
            <version>1.0.2.v20150114</version>
        </dependency>
        <dependency>
            <groupId>org.eclipse.aether</groupId>
            <artifactId>aether-util</artifactId>
            <version>1.0.2.v20150114</version>
        </dependency>

**Comment by skabashnyuk** [comment]
Looks like this is all Eclipse artifacts. Can you confirm?

**Comment by benoitf** [comment]
yes it is for these one

**Comment by skabashnyuk** [comment]
ok.
PR is LGTM

**Comment by benoitf** [comment]
hum sorry this one is not coming from Eclipse it comes from Maven

**Comment by benoitf** [comment]
from Apache Maven. It's the provider for Eclipse Aeather for Maven

**Comment by skabashnyuk** [comment]
Is this artifact comes from Eclipse project?

**Comment by benoitf** [comment]
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=9264

**Comment by skabashnyuk** [comment]
ok. Shall I create CQ for reuse of this artifact or you will?

**Comment by benoitf** [comment]
we need a CQ even if it's already approved ?

**Comment by skabashnyuk** [comment]
yep. We need CQ to approve it for che project. It's so called PB(piggyback )CQs'
For example https://dev.eclipse.org/ipzilla/show_bug.cgi?id=9946 is PB of 
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=9264

**Comment by benoitf** [comment]
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10270

**Comment by skabashnyuk** [comment]
need to fix conflicts

**Comment by benoitf** [comment]
PR rebased

**Pull request merged**
