### PR TITLE
Add versions required for maven plugin creation

### PR DESCRIPTION
**Pull request by benoitf**
Link to IDEX-3240 and plugin mojo

### CODE REVIEW

**Comment by benoitf** [comment]
```       <dependency>
            <groupId>org.apache.maven</groupId>
            <artifactId>maven-core</artifactId>
            <version>${org.apache.maven.maven-core.version}</version>
        </dependency>
        <dependency>
            <groupId>org.codehaus.plexus</groupId>
            <artifactId>plexus-archiver</artifactId>
            <version>${org.codehaus.plexus.plexus-archiver.version}</version>
        </dependency>
        <dependency>
            <groupId>org.apache.maven</groupId>
            <artifactId>maven-plugin-api</artifactId>
            <version>${org.apache.maven.maven-plugin-api.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.maven.plugin-tools</groupId>
            <artifactId>maven-plugin-annotations</artifactId>
            <version>${org.apache.maven.plugin-tools.maven-plugin-annotations.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.maven</groupId>
            <artifactId>maven-compat</artifactId>
            <version>${org.apache.maven.maven-compat.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.apache.maven.plugin-testing</groupId>
            <artifactId>maven-plugin-testing-harness</artifactId>
            <version>${org.apache.maven.plugin-testing.maven-plugin-testing-harness.version}</version>
            <scope>test</scope>
        </dependency>

**Comment by skabashnyuk** [comment]
which of these artifacts will be a part of Che zip(tar)?

**Comment by benoitf** [comment]
It won't be included in che zip or tgz.
It will be stored in nexus repository and then can be used like any maven plugin.

**Comment by skabashnyuk** [comment]
ok is this artifacts produced during che-core che-plugin or che build?

**Pull request merged**
