### PR TITLE
IDEX-3261 Include Dashboard in Eclipse Che

### PR DESCRIPTION
**Pull request by benoitf**

### CODE REVIEW

**Comment by benoitf** [comment]
PR rebased

**Comment by skabashnyuk** [comment]
Are you going to remove this property from codenvy-depmgt pom after?

**Comment by benoitf** [comment]
I guess I will have to replace codenvy.dashboard by che.dashboard where it is used before removing the property but yes, I could make PR about that

**Comment by skabashnyuk** [comment]
+1

**Pull request merged**
